[workspace]

resolver = "2"

members = [

  # maybraid game crates, typically following rfcs  
  "maybraid/richmond/building-components",
  "maybraid/richmond/building-physics",
  "maybraid/richmond/building-shaders",
  "maybraid/richmond/buildings",
  "maybraid/richmond/buildings-playground",
  "maybraid/richmond/developments",
  "maybraid/richmond/development-models",
  "maybraid/richmond/developments-on-terrain-playground",

  "maybraid/menu/components",
  "maybraid/menu/character-ui-menu-renderer",
  "maybraid/menu/screens",
  "maybraid/menu/playground",
  "maybraid/controllers/menu",
  "maybraid/controllers/character",

  "maybraid/scene-ref",
  "maybraid/material-ref",
  "maybraid/terrain-chunk-ref",

  "maybraid/durham/lib",
  "maybraid/durham/shaders",
  "maybraid/durham/models",
  "maybraid/durham/models-playground",
  "maybraid/durham/jersey",
  "maybraid/durham/marazion",

  "maybraid/lod/lib",
  "maybraid/lod/avian",
  "maybraid/lod/cascade",
  "maybraid/lod/cascade-system",
  "maybraid/lod-lazy-refs",

  "maybraid/ground/lib",
  "maybraid/ground/avian",

  "maybraid/sdf/common",
  "maybraid/sdf/common-playground",

  "maybraid/rigs",
  "maybraid/crozon/animations",
  "maybraid/crozon/character-motion",
  "maybraid/crozon/character-ragdoll",
  "maybraid/crozon/bevy-character-ui-menu-renderer",
  "maybraid/crozon/character-concepts-playground",
  "maybraid/crozon/character-world-movements-playground",
  "maybraid/crozon/character-items",
  "maybraid/crozon/character-persist",
  "maybraid/crozon/inventory-user",
  "maybraid/crozon/character-model-user",
  "maybraid/crozon/character-shaders",
  "maybraid/crozon/character-ui-menu",
  "maybraid/crozon/character-ui-menus",
  "maybraid/crozon/characters",
  "maybraid/crozon/rigs",
  "maybraid/crozon/playground",

  "maybraid/procedural/common",

  "maybraid/chico/lib",
  "maybraid/chico/shaders",
  "maybraid/chico/sbs-trees",
  "maybraid/chico/sbs-trees-playground",
  "maybraid/chico/bumpout",
  "maybraid/chico/bumpout-playground",
  "maybraid/chico/vegetation-on-terrain-playground",
  "maybraid/sky/lib",
  "maybraid/world/lib",
  "maybraid/world/playground",
  "maybraid/game",
  "maybraid/input",
  "maybraid/player",
  "maybraid/player-camera",
  "maybraid/movement-realization",
  "maybraid/projectiles",
  "maybraid/damage",
  "maybraid/items/firearms-components",
  "maybraid/items/firearms",
  "maybraid/items/firearm-user",
  "maybraid/items/playground",
  "maybraid/items/firing-range-playground",

  "maybraid/intelligence/movement/lib",
  "maybraid/intelligence/movement/avian",
  "maybraid/intelligence/movement/richmond",
  "maybraid/intelligence/spotting/lib",
  "maybraid/intelligence/spotting/avian",
  "maybraid/intelligence/combat/targeting",
  "maybraid/intelligence/combat/firearm",
  "maybraid/intelligence/evasion",
  "maybraid/intelligence/fleeing",
  "maybraid/intelligence/hiding",
  "maybraid/intelligence/routing",
  "maybraid/intelligence/tether",
  "maybraid/intelligence/poi",
  "maybraid/intelligence/meandering",
  "maybraid/intelligence/journeying",
  "maybraid/intelligence/routing-playground",
  "maybraid/chico/sdf",
  "maybraid/chico/ball-components",
  "maybraid/chico/stick-components",
  "maybraid/chico/tree-components",
  "maybraid/chico/vegetation-components",
  "maybraid/chico/sbs-geometry",
  "maybraid/chico/groves",
  "maybraid/chico/forests",
  "maybraid/gimme/core",
  "maybraid/gimme/gen",

  # legacy still being refactored out: engine
  "engine",

  # playgrounds
  "playgrounds/terrain",
  "playgrounds/objects",
  "playgrounds/skill-map",
  "playgrounds/pathfinding",

  # legacy still being refactored out: procedures
  "procedures/terrain",
  "procedures/vegetation",
  "procedures/buildings",
  "procedures/comproc",
  "procedures/skill-map",
  "procedures/intelligence",

  # general utilities
  ## sdf
  "util/sdf",
  "util/chunk",
  "util/game-commands",
  "util/camera-controls",
  "util/render-item",

  # demos
  "demos/naturescapes"

]

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Movement Labs"]
repository = "www.github.com/ramate-io/wctp"
homepage = "www.github.com/ramate-io/wctp"
publish = false
rust-version = "1.85.0"


[workspace.dependencies]
anyhow = "1.0"
async-stream = "0.3.0"
async-trait = "0.1.71"
clap = { version = "4.4.10", features = ["derive"] }
dotenv = "0.15.0"
futures = "0.3.17"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
thiserror = "1.0.50"
tracing = "0.1.40"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-test = "0.2.5"
tokio = { version = "1.35.1", default-features = false }
tokio-stream = "0.1.15"
hex = { version = "0.4.3", default-features = false, features = [
  "alloc",
  "serde",
] }
zip = { version = "2.4.2", features = ["flate2"] }
walkdir = "2.3.2"
tempfile = "3.5.0"
itertools = "0.14.0"
paste = "1.0"
regex = "1.9.0"
syn = { version = "2.0", features = ["full"] }
quote = "1.0.23"
proc-macro2 = "1.0.32"
proc-macro-error = { version = "1.0.4", features = ["syn-error"] }
strip-ansi-escapes = "0.2.1"
cargo_metadata = "0.19.2"
ignore = "0.4.20"
convert_case = "0.8.0"
toml = "0.8.20"
tonic = "0.12.3"
tonic-build = { version = "0.12.3", features = ["prost"] }
tonic-reflection = "0.12.3"
tonic-web = "0.12.3"
prost = "0.13.3"
leptos = "0.8.8"
leptos_router = "0.8.8"
leptos-use = { version = "0.16", default-features = false, features = [
    "use_raf_fn",
    "use_debounce_fn"
] }
console_error_panic_hook = "0.1"
wasm-bindgen = "0.2"
web-sys = "0.3"
wasm-bindgen-futures = "0.4"
gloo-timers = { version = "0.2" }
chrono = { version = "0.4.41" }
reqwest = { version = "0.12", features = ["json"] }
base64 = "0.22"
bevy = { version = "0.19.0" }
bevy_hanabi = { version = "0.19", default-features = false, features = ["3d"] }
js-sys = "0.3"
log = "0.4"
console_log = "1"
lychee-lib = { git = "https://github.com/lycheeverse/lychee", rev = "d6c2bbe6f1e7b9e83889fc1e7fc675a38a7dd75f" }
comrak = { version = "0.43.0" }
pulldown-cmark = "0.13.0"
rayon = { version = "1.11.0" }
noise = { version = "0.9" }
fastnoise-lite = "1.1.1"
lz4_flex = "0.11"
bincode = "1.3.3"
bevy_math = "0.19.0"

# docs
clap-markdown-ext = { git = "https://github.com/movementlabsxyz/clap-markdown-ext.git", rev = "8f54fe424504bf37fb01dc69aaed8166e429fe6a"}

sdf = { path = "util/sdf" }
render-item = { path = "util/render-item" }
chunk = { path = "util/chunk" }
game-commands = { path = "util/game-commands" }
camera-controls = { path = "util/camera-controls" }
bevy-character-ui-menu-renderer = { path = "maybraid/crozon/bevy-character-ui-menu-renderer" }
character-ui-menu = { path = "maybraid/crozon/character-ui-menu" }

terrain = { path = "procedures/terrain" }
vegetation-sdf = { path = "procedures/vegetation" }
buildings = { path = "procedures/buildings" }
engine = { path = "engine" }
comproc = { "path" = "procedures/comproc" }
skill-map = {"path" = "procedures/skill-map" }

durham-terrain = { path = "maybraid/durham/lib" }
durham-terrain-shaders = { path = "maybraid/durham/shaders" }
durham-terrain-models = { path = "maybraid/durham/models" }
durham-terrain-models-playground = { path = "maybraid/durham/models-playground" }
jersey-terrain-stamps = { path = "maybraid/durham/jersey" }
marazion-watersheds = { path = "maybraid/durham/marazion" }

richmond-building-components = { path = "maybraid/richmond/building-components" }
richmond-building-physics = { path = "maybraid/richmond/building-physics" }
richmond-building-shaders = { path = "maybraid/richmond/building-shaders" }
richmond-buildings = { path = "maybraid/richmond/buildings" }
richmond-buildings-playground = { path = "maybraid/richmond/buildings-playground" }
richmond-developments = { path = "maybraid/richmond/developments" }
richmond-development-models = { path = "maybraid/richmond/development-models" }
richmond-developments-on-terrain-playground = { path = "maybraid/richmond/developments-on-terrain-playground" }

menu-components = { path = "maybraid/menu/components" }
maybraid-character-ui-menu-renderer = { path = "maybraid/menu/character-ui-menu-renderer" }
menu-screens = { path = "maybraid/menu/screens" }
menu-playground = { path = "maybraid/menu/playground" }
maybraid-menu-controller = { path = "maybraid/controllers/menu" }
maybraid-character-controller = { path = "maybraid/controllers/character" }

scene-ref = { path = "maybraid/scene-ref" }
material-ref = { path = "maybraid/material-ref" }
terrain-chunk-ref = { path = "maybraid/terrain-chunk-ref" }

avian3d = "0.7"

lod = { path = "maybraid/lod/lib" }
lod-avian = { path = "maybraid/lod/avian" }
lod-cascade = { path = "maybraid/lod/cascade" }
lod-cascade-system = { path = "maybraid/lod/cascade-system" }
lod-lazy-refs = { path = "maybraid/lod-lazy-refs" }

ground = { path = "maybraid/ground/lib" }
ground-avian = { path = "maybraid/ground/avian" }

sdf-common = { path = "maybraid/sdf/common" }
sdf-common-playground = { path = "maybraid/sdf/common-playground" }
crozon-character-concepts-playground = { path = "maybraid/crozon/character-concepts-playground" }
crozon-character-world-movements-playground = { path = "maybraid/crozon/character-world-movements-playground" }
crozon-character-playground = { path = "maybraid/crozon/playground" }
crozon-character-items = { path = "maybraid/crozon/character-items" }
crozon-character-persist = { path = "maybraid/crozon/character-persist" }
crozon-inventory-user = { path = "maybraid/crozon/inventory-user" }
crozon-character-model-user = { path = "maybraid/crozon/character-model-user" }
crozon-character-shaders = { path = "maybraid/crozon/character-shaders" }
crozon-character-ui-menus = { path = "maybraid/crozon/character-ui-menus" }
crozon-characters = { path = "maybraid/crozon/characters" }
crozon-character-motion = { path = "maybraid/crozon/character-motion" }
crozon-character-ragdoll = { path = "maybraid/crozon/character-ragdoll" }
rigs = { path = "maybraid/rigs" }
crozon-rigs = { path = "maybraid/crozon/rigs" }
malo-animations = { path = "maybraid/crozon/animations" }
procedural-common = { path = "maybraid/procedural/common" }

chico = { path = "maybraid/chico/lib" }
chico-bumpout = { path = "maybraid/chico/bumpout" }
chico-sbs-trees = { path = "maybraid/chico/sbs-trees" }
chico-sdf = { path = "maybraid/chico/sdf" }
chico-ball-components = { path = "maybraid/chico/ball-components" }
chico-stick-components = { path = "maybraid/chico/stick-components" }
chico-tree-components = { path = "maybraid/chico/tree-components" }
chico-vegetation-components = { path = "maybraid/chico/vegetation-components" }
chico-sbs-geometry = { path = "maybraid/chico/sbs-geometry" }
chico-groves = { path = "maybraid/chico/groves" }
chico-forests = { path = "maybraid/chico/forests" }
chico-vegetation-shaders = { path = "maybraid/chico/shaders" }
chico-vegetation-on-terrain-playground = { path = "maybraid/chico/vegetation-on-terrain-playground" }
maybraid-sky = { path = "maybraid/sky/lib" }
maybraid-world = { path = "maybraid/world/lib" }
maybraid = { path = "maybraid/game" }
maybraid-input = { path = "maybraid/input" }
player = { path = "maybraid/player" }
player-camera = { path = "maybraid/player-camera" }
movement-realization = { path = "maybraid/movement-realization" }
projectiles = { path = "maybraid/projectiles" }
damage = { path = "maybraid/damage" }
firearms-components = { path = "maybraid/items/firearms-components" }
firearms = { path = "maybraid/items/firearms" }
firearm-user = { path = "maybraid/items/firearm-user" }
movement-intelligence = { path = "maybraid/intelligence/movement/lib" }
movement-intelligence-avian = { path = "maybraid/intelligence/movement/avian" }
movement-intelligence-richmond = { path = "maybraid/intelligence/movement/richmond" }
spotting-intelligence = { path = "maybraid/intelligence/spotting/lib" }
spotting-intelligence-avian = { path = "maybraid/intelligence/spotting/avian" }
combat-targeting = { path = "maybraid/intelligence/combat/targeting" }
firearm-intelligence = { path = "maybraid/intelligence/combat/firearm" }
evasion-intelligence = { path = "maybraid/intelligence/evasion" }
fleeing-intelligence = { path = "maybraid/intelligence/fleeing" }
hiding-intelligence = { path = "maybraid/intelligence/hiding" }
routing-intelligence = { path = "maybraid/intelligence/routing" }
tether-intelligence = { path = "maybraid/intelligence/tether" }
poi-intelligence = { path = "maybraid/intelligence/poi" }
meandering-intelligence = { path = "maybraid/intelligence/meandering" }
journeying-intelligence = { path = "maybraid/intelligence/journeying" }
routing-playground = { path = "maybraid/intelligence/routing-playground" }
items-playground = { path = "maybraid/items/playground" }
firing-range-playground = { path = "maybraid/items/firing-range-playground" }

gimme-core = { path = "maybraid/gimme/core" }
gimme-gen = { path = "maybraid/gimme/gen" }

[workspace.lints.clippy]
debug_assert_with_mut_call = "deny"
inefficient_to_string = "deny"
map_flatten = "deny"
manual_ok_or = "deny"
doc_link_with_quotes = "deny"
match_same_arms = "deny"
semicolon_if_nothing_returned = "deny"
unwrap_used = "warn"
expect_used = "warn"

[profile.dev]
panic = "unwind"

[profile.release.build-override]
opt-level = 3

[profile.perf]
inherits = "release"
codegen-units = 1
lto = "thin"


[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
