use crozon_character_items::{ClothingMesh, ItemColor};
use crozon_characters::{
	presets::{BuildPreset, GenderPreset},
	species::{
		brodler::{
			assets::HornMesh, BrodlerEyeColor, BrodlerHeadMesh, BrodlerHornColor, BrodlerSkinColor,
		},
		brenal::{BrenalBodyMesh, BrenalHeadMesh, BrenalMouthMesh},
		caole::{CaoleBodyMesh, CaoleMouthMesh},
		hars::{HarsBodyMesh, HarsMouthMesh},
		ylter::{YilterBodyMesh, YilterMouthMesh},
		sonyak::{SonyakBodyMesh, SonyakMouthMesh},
		claber::{ClaberBodyMesh, ClaberColor, ClaberHeadMesh, ClaberMouthMesh},
		croconot::{CroconotBodyMesh, CroconotHeadMesh, CroconotMouthMesh},
		common::{BodyMesh, EarMesh, EyeMesh, HairMesh, HeadMesh, MouthMesh, NoseMesh},
		dui::{DuiEyeMesh, DuiHeadMesh, DuiMouthColor, DuiMouthMesh, DuiSkinColor},
		lero::{
			LeroEyeColor, LeroHeadMesh, LeroMouthColor, LeroMouthMesh, LeroSkinColor,
			LeroSpineColor, LeroTailColor,
		},
		mygr::{MygrEyeColor, MygrHeadMesh, MygrMouthMesh, MygrSkinColor},
		spibmom::{
			SpibmomCrownColor, SpibmomEarColor, SpibmomEyeColor, SpibmomHeadMesh,
			SpibmomMouthColor, SpibmomMouthMesh, SpibmomSkinColor, SpibmomSpineColor,
		},
		wumbus::{
			WumbusEarColor, WumbusEyeColor, WumbusHeadMesh, WumbusHornColor, WumbusMouthColor,
			WumbusMouthMesh, WumbusSkinColor, WumbusSpineColor,
		},
	},
	ConceptAnimation,
};

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum SectionId {
	Presets,
	Head,
	Body,
	HeadFeatures,
	Hair,
	Clothing,
	Animation,
}

impl SectionId {
	pub const fn label(self) -> &'static str {
		match self {
			Self::Presets => "Presets",
			Self::Head => "Head",
			Self::Body => "Body",
			Self::HeadFeatures => "Head & Features",
			Self::Hair => "Hair",
			Self::Clothing => "Clothing",
			Self::Animation => "Animation",
		}
	}
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum CharacterField {
	Gender,
	Build,
	BodyMesh,
	HeadMesh,
	BrodlerHead,
	Horns,
	MygrHead,
	MygrMouth,
	WumbusHead,
	WumbusMouth,
	WumbusHorns,
	BrenalBody,
	BrenalHead,
	BrenalHorns,
	BrenalMouth,
	CaoleBody,
	CaoleMouth,
	HarsBody,
	HarsMouth,
	YilterBody,
	YilterMouth,
	SonyakBody,
	SonyakMouth,
	ClaberBody,
	ClaberHead,
	ClaberHorns,
	ClaberMouth,
	CroconotBody,
	CroconotHead,
	CroconotHorns,
	CroconotMouth,
	DuiHead,
	DuiEye,
	DuiNose,
	DuiMouth,
	Eye,
	Nose,
	Mouth,
	Ear,
	Hair,
	Animation,
	BodyColor,
	EyeColor,
	MouthColor,
	HairColor,
	SkinColor,
	BrodlerEyeColor,
	HornColor,
	MygrSkinColor,
	MygrEyeColor,
	WumbusSkinColor,
	WumbusEyeColor,
	WumbusEarColor,
	WumbusMouthColor,
	WumbusHornColor,
	WumbusSpineColor,
	DuiSkinColor,
	DuiMouthColor,
	LeroHead,
	LeroMouth,
	LeroMouthColor,
	LeroSkinColor,
	LeroEyeColor,
	LeroTailColor,
	TailColor,
	LeroSpineColor,
	SpibmomHead,
	SpibmomMouth,
	SpibmomSkinColor,
	SpibmomEyeColor,
	SpibmomEarColor,
	SpibmomMouthColor,
	SpibmomCrownColor,
	SpibmomSpineColor,
	Clothing(ClothingMesh),
	ShoulderWidth,
	HipWidth,
	ChestThickness,
	HipThickness,
	LegThickness,
	ButtocksThickness,
	WaistThickness,
	LowerTrunkThickness,
	ArmLength,
	ArmThickness,
	LegLength,
	EyeWidth,
	EyeHeight,
	EyeTilt,
	NoseWidth,
	NoseHeight,
	MouthWidth,
	MouthHeight,
	EarWidth,
	EarHeight,
	SnoutLength,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum AssetValue {
	Gender(GenderPreset),
	Build(BuildPreset),
	Body(BodyMesh),
	Head(HeadMesh),
	BrodlerHead(BrodlerHeadMesh),
	Horns(HornMesh),
	MygrHead(MygrHeadMesh),
	MygrMouth(MygrMouthMesh),
	WumbusHead(WumbusHeadMesh),
	WumbusMouth(WumbusMouthMesh),
	BrenalBody(BrenalBodyMesh),
	BrenalHead(BrenalHeadMesh),
	BrenalMouth(BrenalMouthMesh),
	CaoleBody(CaoleBodyMesh),
	CaoleMouth(CaoleMouthMesh),
	HarsBody(HarsBodyMesh),
	HarsMouth(HarsMouthMesh),
	YilterBody(YilterBodyMesh),
	YilterMouth(YilterMouthMesh),
	SonyakBody(SonyakBodyMesh),
	SonyakMouth(SonyakMouthMesh),
	ClaberBody(ClaberBodyMesh),
	ClaberHead(ClaberHeadMesh),
	ClaberMouth(ClaberMouthMesh),
	CroconotBody(CroconotBodyMesh),
	CroconotHead(CroconotHeadMesh),
	CroconotMouth(CroconotMouthMesh),
	LeroHead(LeroHeadMesh),
	LeroMouth(LeroMouthMesh),
	SpibmomHead(SpibmomHeadMesh),
	SpibmomMouth(SpibmomMouthMesh),
	DuiHead(DuiHeadMesh),
	DuiEye(DuiEyeMesh),
	DuiMouth(DuiMouthMesh),
	Eye(EyeMesh),
	Nose(NoseMesh),
	Mouth(MouthMesh),
	Ear(EarMesh),
	Hair(HairMesh),
	Animation(ConceptAnimation),
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SwatchValue {
	/// Shared item palette: hair everywhere, plus Braidman body/eye/mouth.
	Item(ItemColor),
	BrodlerSkin(BrodlerSkinColor),
	BrodlerEye(BrodlerEyeColor),
	BrodlerHorn(BrodlerHornColor),
	MygrSkin(MygrSkinColor),
	MygrEye(MygrEyeColor),
	WumbusSkin(WumbusSkinColor),
	WumbusEye(WumbusEyeColor),
	WumbusEar(WumbusEarColor),
	WumbusMouth(WumbusMouthColor),
	WumbusHorn(WumbusHornColor),
	WumbusSpine(WumbusSpineColor),
	DuiSkin(DuiSkinColor),
	DuiMouth(DuiMouthColor),
	Claber(ClaberColor),
	LeroSkin(LeroSkinColor),
	LeroEye(LeroEyeColor),
	LeroMouthColor(LeroMouthColor),
	LeroTail(LeroTailColor),
	LeroSpine(LeroSpineColor),
	SpibmomSkin(SpibmomSkinColor),
	SpibmomEye(SpibmomEyeColor),
	SpibmomEar(SpibmomEarColor),
	SpibmomMouthColor(SpibmomMouthColor),
	SpibmomCrown(SpibmomCrownColor),
	SpibmomSpine(SpibmomSpineColor),
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub enum MenuEvent {
	ToggleSection(SectionId),
	SetSpecies(crate::character::ConceptSpecies),
	Cycle(CharacterField, i32),
	SetAsset(CharacterField, AssetValue),
	SliderDelta(CharacterField, f32),
	ToggleClothing(ClothingMesh),
	SetSwatch(CharacterField, SwatchValue),
}
