use crozon_character_items::{ClothingMesh, ItemColor};
use crozon_characters::{
	presets::{BuildPreset, GenderPreset},
	species::{
		brodler::{
			assets::HornMesh, BrodlerEyeColor, BrodlerHeadMesh, BrodlerHornColor, BrodlerSkinColor,
		},
		brenal::{BrenalBodyMesh, BrenalHeadMesh, BrenalMouthMesh},
		caole::{CaoleBodyMesh, CaoleMouthMesh},
		epiphant::{EpiphantBodyMesh, EpiphantColor, EpiphantNoseMesh},
		hars::{HarsBodyMesh, HarsMouthMesh},
		ylter::{YilterBodyMesh, YilterMouthMesh},
		sonyak::{SonyakBodyMesh, SonyakMouthMesh},
		claber::{ClaberBodyMesh, ClaberColor, ClaberHeadMesh, ClaberMouthMesh},
		croconot::{CroconotBodyMesh, CroconotHeadMesh, CroconotMouthMesh},
		common::{BodyMesh, EarMesh, EyeMesh, HairMesh, HeadMesh, MouthMesh, NoseMesh},
		dui::{DuiEyeMesh, DuiHeadMesh, DuiMouthColor, DuiMouthMesh, DuiSkinColor},
		brokker::{
			BrokkerEyeColor, BrokkerHeadMesh, BrokkerPlumageColor, BrokkerSnoutColor,
		},
		lidder::{LidderBeakColor, LidderBeakMesh, LidderEyeColor, LidderHeadMesh, LidderPlumageColor},
		chupri::{ChupriBeakColor, ChupriBeakMesh, ChupriEyeColor, ChupriHeadMesh, ChupriPlumageColor},
		kispar::{
			KisparBeakColor, KisparBeakMesh, KisparEyeColor, KisparHeadMesh, KisparPlumageColor,
		},
		tapp::{
			TappBeakColor, TappBeakMesh, TappEyeColor, TappHeadMesh, TappPlumageColor,
		},
		kaller::{
			KallerCrownColor, KallerEyeColor, KallerHeadMesh, KallerPlumageColor, KallerSnoutColor,
		},
		kappler::{
			KapplerBeakColor, KapplerBeakMesh, KapplerEyeColor, KapplerHeadMesh, KapplerPlumageColor,
		},
		lero::{
			LeroEyeColor, LeroHeadMesh, LeroMouthColor, LeroMouthMesh, LeroSkinColor,
			LeroSpineColor, LeroTailColor,
		},
		mygr::{MygrEyeColor, MygrHeadMesh, MygrMouthMesh, MygrSkinColor},
		spibmom::{
			SpibmomCrownColor, SpibmomEarColor, SpibmomEyeColor, SpibmomHeadMesh,
			SpibmomMouthColor, SpibmomMouthMesh, SpibmomSkinColor, SpibmomSpineColor,
		},
		tipple::{
			TippleBeakColor, TippleBeakMesh, TippleEyeColor, TippleHeadMesh, TipplePlumageColor,
		},
		topple::{
			ToppleBeakColor, ToppleBeakMesh, ToppleEyeColor, ToppleHeadMesh, TopplePlumageColor,
		},
		tuberwaber::{TuberwaberBodyMesh, TuberwaberColor, TuberwaberHeadMesh},
		wumbus::{
			WumbusEarColor, WumbusEyeColor, WumbusHeadMesh, WumbusHornColor, WumbusMouthColor,
			WumbusMouthMesh, WumbusSkinColor, WumbusSpineColor,
		},
	},
	ConceptAnimation,
};

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum SectionId {
	Presets,
	Head,
	Body,
	HeadFeatures,
	Hair,
	Clothing,
	Animation,
}

impl SectionId {
	pub const fn label(self) -> &'static str {
		match self {
			Self::Presets => "Presets",
			Self::Head => "Head",
			Self::Body => "Body",
			Self::HeadFeatures => "Head & Features",
			Self::Hair => "Hair",
			Self::Clothing => "Clothing",
			Self::Animation => "Animation",
		}
	}
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum CharacterField {
	Gender,
	Build,
	BodyMesh,
	HeadMesh,
	BrodlerHead,
	Horns,
	MygrHead,
	MygrMouth,
	WumbusHead,
	WumbusMouth,
	WumbusHorns,
	BrenalBody,
	BrenalHead,
	BrenalHorns,
	BrenalMouth,
	CaoleBody,
	CaoleMouth,
	EpiphantBody,
	EpiphantNose,
	TuberwaberBody,
	TuberwaberHead,
	HarsBody,
	HarsMouth,
	YilterBody,
	YilterMouth,
	SonyakBody,
	SonyakMouth,
	ClaberBody,
	ClaberHead,
	ClaberHorns,
	ClaberMouth,
	CroconotBody,
	CroconotHead,
	CroconotHorns,
	CroconotMouth,
	DuiHead,
	DuiEye,
	DuiNose,
	DuiMouth,
	LidderHead,
	LidderBeak,
	LidderPlumageColor,
	LidderEyeColor,
	LidderBeakColor,
	ChupriHead,
	ChupriBeak,
	ChupriPlumageColor,
	ChupriEyeColor,
	ChupriBeakColor,
	BrokkerHead,
	BrokkerPlumageColor,
	BrokkerEyeColor,
	BrokkerSnoutColor,
	TippleHead,
	TippleBeak,
	TipplePlumageColor,
	TippleEyeColor,
	TippleBeakColor,
	ToppleHead,
	ToppleBeak,
	TopplePlumageColor,
	ToppleEyeColor,
	ToppleBeakColor,
	KisparHead,
	KisparBeak,
	KisparPlumageColor,
	KisparEyeColor,
	KisparBeakColor,
	TappHead,
	TappBeak,
	TappPlumageColor,
	TappEyeColor,
	TappBeakColor,
	KallerHead,
	KallerPlumageColor,
	KallerEyeColor,
	KallerSnoutColor,
	KallerCrownColor,
	KapplerHead,
	KapplerBeak,
	KapplerPlumageColor,
	KapplerEyeColor,
	KapplerBeakColor,
	Eye,
	Nose,
	Mouth,
	Ear,
	Hair,
	Animation,
	BodyColor,
	EyeColor,
	MouthColor,
	NoseColor,
	EarColor,
	HairColor,
	SkinColor,
	BrodlerEyeColor,
	HornColor,
	MygrSkinColor,
	MygrEyeColor,
	WumbusSkinColor,
	WumbusEyeColor,
	WumbusEarColor,
	WumbusMouthColor,
	WumbusHornColor,
	WumbusSpineColor,
	DuiSkinColor,
	DuiMouthColor,
	LeroHead,
	LeroMouth,
	LeroMouthColor,
	LeroSkinColor,
	LeroEyeColor,
	LeroTailColor,
	TailColor,
	LeroSpineColor,
	SpibmomHead,
	SpibmomMouth,
	SpibmomSkinColor,
	SpibmomEyeColor,
	SpibmomEarColor,
	SpibmomMouthColor,
	SpibmomCrownColor,
	SpibmomSpineColor,
	Clothing(ClothingMesh),
	ShoulderWidth,
	HipWidth,
	ChestThickness,
	HipThickness,
	LegThickness,
	ButtocksThickness,
	WaistThickness,
	LowerTrunkThickness,
	ArmLength,
	ArmThickness,
	LegLength,
	EyeWidth,
	EyeHeight,
	EyeTilt,
	NoseWidth,
	NoseHeight,
	MouthWidth,
	MouthHeight,
	EarWidth,
	EarHeight,
	SnoutLength,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum AssetValue {
	Gender(GenderPreset),
	Build(BuildPreset),
	Body(BodyMesh),
	Head(HeadMesh),
	BrodlerHead(BrodlerHeadMesh),
	Horns(HornMesh),
	MygrHead(MygrHeadMesh),
	MygrMouth(MygrMouthMesh),
	WumbusHead(WumbusHeadMesh),
	WumbusMouth(WumbusMouthMesh),
	BrenalBody(BrenalBodyMesh),
	BrenalHead(BrenalHeadMesh),
	BrenalMouth(BrenalMouthMesh),
	CaoleBody(CaoleBodyMesh),
	CaoleMouth(CaoleMouthMesh),
	EpiphantBody(EpiphantBodyMesh),
	EpiphantNose(EpiphantNoseMesh),
	TuberwaberBody(TuberwaberBodyMesh),
	TuberwaberHead(TuberwaberHeadMesh),
	HarsBody(HarsBodyMesh),
	HarsMouth(HarsMouthMesh),
	YilterBody(YilterBodyMesh),
	YilterMouth(YilterMouthMesh),
	SonyakBody(SonyakBodyMesh),
	SonyakMouth(SonyakMouthMesh),
	ClaberBody(ClaberBodyMesh),
	ClaberHead(ClaberHeadMesh),
	ClaberMouth(ClaberMouthMesh),
	CroconotBody(CroconotBodyMesh),
	CroconotHead(CroconotHeadMesh),
	CroconotMouth(CroconotMouthMesh),
	LeroHead(LeroHeadMesh),
	LeroMouth(LeroMouthMesh),
	SpibmomHead(SpibmomHeadMesh),
	SpibmomMouth(SpibmomMouthMesh),
	DuiHead(DuiHeadMesh),
	DuiEye(DuiEyeMesh),
	DuiMouth(DuiMouthMesh),
	LidderHead(LidderHeadMesh),
	LidderBeak(LidderBeakMesh),
	ChupriHead(ChupriHeadMesh),
	ChupriBeak(ChupriBeakMesh),
	BrokkerHead(BrokkerHeadMesh),
	TippleHead(TippleHeadMesh),
	TippleBeak(TippleBeakMesh),
	ToppleHead(ToppleHeadMesh),
	ToppleBeak(ToppleBeakMesh),
	KisparHead(KisparHeadMesh),
	KisparBeak(KisparBeakMesh),
	TappHead(TappHeadMesh),
	TappBeak(TappBeakMesh),
	KallerHead(KallerHeadMesh),
	KapplerHead(KapplerHeadMesh),
	KapplerBeak(KapplerBeakMesh),
	Eye(EyeMesh),
	Nose(NoseMesh),
	Mouth(MouthMesh),
	Ear(EarMesh),
	Hair(HairMesh),
	Animation(ConceptAnimation),
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SwatchValue {
	/// Shared item palette: hair everywhere, plus Braidman body/eye/mouth.
	Item(ItemColor),
	BrodlerSkin(BrodlerSkinColor),
	BrodlerEye(BrodlerEyeColor),
	BrodlerHorn(BrodlerHornColor),
	MygrSkin(MygrSkinColor),
	MygrEye(MygrEyeColor),
	WumbusSkin(WumbusSkinColor),
	WumbusEye(WumbusEyeColor),
	WumbusEar(WumbusEarColor),
	WumbusMouth(WumbusMouthColor),
	WumbusHorn(WumbusHornColor),
	WumbusSpine(WumbusSpineColor),
	DuiSkin(DuiSkinColor),
	DuiMouth(DuiMouthColor),
	LidderPlumage(LidderPlumageColor),
	LidderEye(LidderEyeColor),
	LidderBeak(LidderBeakColor),
	ChupriPlumage(ChupriPlumageColor),
	ChupriEye(ChupriEyeColor),
	ChupriBeak(ChupriBeakColor),
	BrokkerPlumage(BrokkerPlumageColor),
	BrokkerEye(BrokkerEyeColor),
	BrokkerSnout(BrokkerSnoutColor),
	TipplePlumage(TipplePlumageColor),
	TippleEye(TippleEyeColor),
	TippleBeak(TippleBeakColor),
	TopplePlumage(TopplePlumageColor),
	ToppleEye(ToppleEyeColor),
	ToppleBeak(ToppleBeakColor),
	KisparPlumage(KisparPlumageColor),
	KisparEye(KisparEyeColor),
	KisparBeak(KisparBeakColor),
	TappPlumage(TappPlumageColor),
	TappEye(TappEyeColor),
	TappBeak(TappBeakColor),
	KallerPlumage(KallerPlumageColor),
	KallerEye(KallerEyeColor),
	KallerSnout(KallerSnoutColor),
	KallerCrown(KallerCrownColor),
	KapplerPlumage(KapplerPlumageColor),
	KapplerEye(KapplerEyeColor),
	KapplerBeak(KapplerBeakColor),
	Claber(ClaberColor),
	Epiphant(EpiphantColor),
	Tuberwaber(TuberwaberColor),
	LeroSkin(LeroSkinColor),
	LeroEye(LeroEyeColor),
	LeroMouthColor(LeroMouthColor),
	LeroTail(LeroTailColor),
	LeroSpine(LeroSpineColor),
	SpibmomSkin(SpibmomSkinColor),
	SpibmomEye(SpibmomEyeColor),
	SpibmomEar(SpibmomEarColor),
	SpibmomMouthColor(SpibmomMouthColor),
	SpibmomCrown(SpibmomCrownColor),
	SpibmomSpine(SpibmomSpineColor),
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub enum MenuEvent {
	ToggleSection(SectionId),
	SetSpecies(crate::character::ConceptSpecies),
	Cycle(CharacterField, i32),
	SetAsset(CharacterField, AssetValue),
	SliderDelta(CharacterField, f32),
	ToggleClothing(ClothingMesh),
	SetSwatch(CharacterField, SwatchValue),
}
