[package]
name = "chico-groves"
version = { workspace = true }
edition  = { workspace = true }
license  = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[dependencies]
bevy_math = { workspace = true }
procedural-common = { workspace = true }
gimme-gen = { workspace = true }
log = { workspace = true }
chico-sbs-geometry = { workspace = true }
chico-tree-components = { workspace = true }
bevy = { workspace = true, optional = true }
chico-ball-components = { workspace = true, optional = true }
chico-sbs-trees = { workspace = true, optional = true }
chico-vegetation-shaders = { workspace = true, optional = true }
clap = { workspace = true, optional = true }

[features]
default = []
render = [
	"dep:bevy",
	"dep:chico-ball-components",
	"dep:chico-sbs-trees",
	"dep:chico-vegetation-shaders",
	"dep:clap",
	"procedural-common/clap",
]
clap = ["render"]

[dev-dependencies]
anyhow = { workspace = true }

[lints]
workspace = true
