[package]
name = "chico-groves"
version = { workspace = true }
edition  = { workspace = true }
license  = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[dependencies]
bevy_math = { workspace = true }
clap = { workspace = true, optional = true }
procedural-common = { workspace = true }
bevy = { workspace = true, optional = true }
render-item = { workspace = true, optional = true  }
chico-ball-components = { workspace = true, optional = true }
chico-sbs-geometry = { workspace = true, optional = true, features = ["clap", "render"] }
chico-sbs-trees = { workspace = true, optional = true }
log = { workspace = true }
gimme-gen = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }

[features]
default = [ "render" ]
render = [
	"dep:bevy",
	"dep:render-item",
	"dep:chico-ball-components",
	"dep:chico-sbs-geometry",
	"dep:chico-sbs-trees",
	"dep:clap",
	"procedural-common/clap",
]
clap = [ "render" ]

[lints]
workspace = true
