[package]
name = "maybraid-world"
version = { workspace = true }
edition  = { workspace = true }
license  = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[dependencies]
avian3d = { workspace = true }
bevy = { workspace = true }
chico-forests = { workspace = true }
chico-vegetation-components = { workspace = true }
clap = { workspace = true }
combat-hud = { workspace = true }
crozon-character-items = { workspace = true }
crozon-characters = { workspace = true }
crozon-inventory-user = { workspace = true }
damage = { workspace = true }
durham-terrain-models = { workspace = true }
evasion-intelligence = { workspace = true }
firearm-intelligence = { workspace = true }
firearm-user = { workspace = true }
firearms = { workspace = true }
fleeing-intelligence = { workspace = true }
game-commands = { workspace = true }
ground-avian = { workspace = true }
hiding-intelligence = { workspace = true }
log = { workspace = true }
lod = { workspace = true }
lod-avian = { workspace = true }
material-ref = { workspace = true }
maybraid-character-controller = { workspace = true }
maybraid-input = { workspace = true }
maybraid-sky = { workspace = true }
maybraid-mobs = { workspace = true }
player = { workspace = true }
player-camera = { workspace = true }
mob-characters = { workspace = true }
mob-groups = { workspace = true }
meandering-intelligence = { workspace = true }
movement-intelligence = { workspace = true }
movement-intelligence-avian = { workspace = true }
movement-realization = { workspace = true }
poi-intelligence = { workspace = true }
procedural-common = { workspace = true }
chico-vegetation-on-terrain-playground = { workspace = true }
richmond-development-models = { workspace = true }
richmond-developments-on-terrain-playground = { workspace = true }
richmond-urbanization = { workspace = true }
routing-intelligence = { workspace = true }
spotting-intelligence = { workspace = true }
threat-intelligence = { workspace = true }
threat-intelligence-damage = { workspace = true }
threat-management-intelligence = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }

[lints]
workspace = true
