[package]
name = "maybraid-world"
version = { workspace = true }
edition  = { workspace = true }
license  = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[dependencies]
bevy = { workspace = true }
clap = { workspace = true }
game-commands = { workspace = true }
log = { workspace = true }
lod = { workspace = true }
maybraid-sky = { workspace = true }
chico-vegetation-on-terrain-playground = { workspace = true }

[lints]
workspace = true
