//! Shared preview color for material and thumbnail tinting.

use bevy::prelude::*;
use crozon_character_items::ItemColor;
use crozon_characters::species::{
	brodler::{BrodlerEyeColor, BrodlerHornColor, BrodlerSkinColor},
	claber::ClaberColor,
	epiphant::EpiphantColor,
	tuberwaber::TuberwaberColor,
	dui::{DuiEyeColor, DuiMouthColor, DuiNoseColor, DuiSkinColor},
	lidder::{LidderBeakColor, LidderEyeColor, LidderPlumageColor},
	chupri::{ChupriBeakColor, ChupriEyeColor, ChupriPlumageColor},
	brokker::{BrokkerEyeColor, BrokkerPlumageColor, BrokkerSnoutColor},
	tipple::{TippleBeakColor, TippleEyeColor, TipplePlumageColor},
	topple::{ToppleBeakColor, ToppleEyeColor, TopplePlumageColor},
	kispar::{KisparBeakColor, KisparEyeColor, KisparPlumageColor},
	tapp::{TappBeakColor, TappEyeColor, TappPlumageColor},
	kaller::{KallerCrownColor, KallerEyeColor, KallerPlumageColor, KallerSnoutColor},
	kappler::{KapplerBeakColor, KapplerEyeColor, KapplerPlumageColor},
	lero::{LeroEyeColor, LeroMouthColor, LeroSkinColor, LeroSpineColor, LeroTailColor},
	mygr::{MygrEyeColor, MygrSkinColor},
	spibmom::{
		SpibmomCrownColor, SpibmomEarColor, SpibmomEyeColor, SpibmomMouthColor, SpibmomSkinColor,
		SpibmomSpineColor,
	},
	wumbus::{
		WumbusEarColor, WumbusEyeColor, WumbusHornColor, WumbusMouthColor, WumbusSkinColor,
		WumbusSpineColor,
	},
};

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum PreviewColor {
	/// Shared item palette: hair everywhere, plus Braidman body/eye/mouth.
	Item(ItemColor),
	BrodlerSkin(BrodlerSkinColor),
	BrodlerEye(BrodlerEyeColor),
	BrodlerHorn(BrodlerHornColor),
	MygrSkin(MygrSkinColor),
	MygrEye(MygrEyeColor),
	DuiSkin(DuiSkinColor),
	DuiEye(DuiEyeColor),
	DuiNose(DuiNoseColor),
	DuiMouth(DuiMouthColor),
	LidderPlumage(LidderPlumageColor),
	LidderEye(LidderEyeColor),
	LidderBeak(LidderBeakColor),
	ChupriPlumage(ChupriPlumageColor),
	ChupriEye(ChupriEyeColor),
	ChupriBeak(ChupriBeakColor),
	BrokkerPlumage(BrokkerPlumageColor),
	BrokkerEye(BrokkerEyeColor),
	BrokkerSnout(BrokkerSnoutColor),
	TipplePlumage(TipplePlumageColor),
	TippleEye(TippleEyeColor),
	TippleBeak(TippleBeakColor),
	TopplePlumage(TopplePlumageColor),
	ToppleEye(ToppleEyeColor),
	ToppleBeak(ToppleBeakColor),
	KisparPlumage(KisparPlumageColor),
	KisparEye(KisparEyeColor),
	KisparBeak(KisparBeakColor),
	TappPlumage(TappPlumageColor),
	TappEye(TappEyeColor),
	TappBeak(TappBeakColor),
	KallerPlumage(KallerPlumageColor),
	KallerEye(KallerEyeColor),
	KallerSnout(KallerSnoutColor),
	KallerCrown(KallerCrownColor),
	KapplerPlumage(KapplerPlumageColor),
	KapplerEye(KapplerEyeColor),
	KapplerBeak(KapplerBeakColor),
	Claber(ClaberColor),
	Epiphant(EpiphantColor),
	Tuberwaber(TuberwaberColor),
	WumbusSkin(WumbusSkinColor),
	WumbusEye(WumbusEyeColor),
	WumbusEar(WumbusEarColor),
	WumbusMouth(WumbusMouthColor),
	WumbusHorn(WumbusHornColor),
	WumbusSpine(WumbusSpineColor),
	LeroSkin(LeroSkinColor),
	LeroEye(LeroEyeColor),
	LeroMouth(LeroMouthColor),
	LeroTail(LeroTailColor),
	LeroSpine(LeroSpineColor),
	SpibmomSkin(SpibmomSkinColor),
	SpibmomEye(SpibmomEyeColor),
	SpibmomEar(SpibmomEarColor),
	SpibmomMouth(SpibmomMouthColor),
	SpibmomCrown(SpibmomCrownColor),
	SpibmomSpine(SpibmomSpineColor),
}

impl PreviewColor {
	pub fn bevy_color(self) -> Color {
		match self {
			Self::Item(color) => color.color(),
			Self::BrodlerSkin(color) => color.color(),
			Self::BrodlerEye(color) => color.color(),
			Self::BrodlerHorn(color) => color.color(),
			Self::MygrSkin(color) => color.color(),
			Self::MygrEye(color) => color.color(),
			Self::DuiSkin(color) => color.color(),
			Self::DuiEye(color) => color.color(),
			Self::DuiNose(color) => color.color(),
			Self::DuiMouth(color) => color.color(),
			Self::LidderPlumage(color) => color.color(),
			Self::LidderEye(color) => color.color(),
			Self::LidderBeak(color) => color.color(),
			Self::ChupriPlumage(color) => color.color(),
			Self::ChupriEye(color) => color.color(),
			Self::ChupriBeak(color) => color.color(),
			Self::BrokkerPlumage(color) => color.color(),
			Self::BrokkerEye(color) => color.color(),
			Self::BrokkerSnout(color) => color.color(),
			Self::TipplePlumage(color) => color.color(),
			Self::TippleEye(color) => color.color(),
			Self::TippleBeak(color) => color.color(),
			Self::TopplePlumage(color) => color.color(),
			Self::ToppleEye(color) => color.color(),
			Self::ToppleBeak(color) => color.color(),
			Self::KisparPlumage(color) => color.color(),
			Self::KisparEye(color) => color.color(),
			Self::KisparBeak(color) => color.color(),
			Self::TappPlumage(color) => color.color(),
			Self::TappEye(color) => color.color(),
			Self::TappBeak(color) => color.color(),
			Self::KallerPlumage(color) => color.color(),
			Self::KallerEye(color) => color.color(),
			Self::KallerSnout(color) => color.color(),
			Self::KallerCrown(color) => color.color(),
			Self::KapplerPlumage(color) => color.color(),
			Self::KapplerEye(color) => color.color(),
			Self::KapplerBeak(color) => color.color(),
			Self::Claber(color) => color.color(),
			Self::Epiphant(color) => color.color(),
			Self::Tuberwaber(color) => color.color(),
			Self::WumbusSkin(color) => color.color(),
			Self::WumbusEye(color) => color.color(),
			Self::WumbusEar(color) => color.color(),
			Self::WumbusMouth(color) => color.color(),
			Self::WumbusHorn(color) => color.color(),
			Self::WumbusSpine(color) => color.color(),
			Self::LeroSkin(color) => color.color(),
			Self::LeroEye(color) => color.color(),
			Self::LeroMouth(color) => color.color(),
			Self::LeroTail(color) => color.color(),
			Self::LeroSpine(color) => color.color(),
			Self::SpibmomSkin(color) => color.color(),
			Self::SpibmomEye(color) => color.color(),
			Self::SpibmomEar(color) => color.color(),
			Self::SpibmomMouth(color) => color.color(),
			Self::SpibmomCrown(color) => color.color(),
			Self::SpibmomSpine(color) => color.color(),
		}
	}
}
