[package]
name = "richmond-buildings-playground"
version = { workspace = true }
edition  = { workspace = true }
license  = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[[bin]]
name = "richmond-buildings-playground"
path = "src/main.rs"

[dependencies]
# `trace` enables bevy_ecs `system_commands` spans used to time command apply.
avian3d = { workspace = true }
bevy = { workspace = true, features = ["trace"] }
bevy_math = { workspace = true }
clap = { workspace = true }
game-commands = { workspace = true }
log = { workspace = true }
lod = { workspace = true }
lod-avian = { workspace = true }
scene-ref = { workspace = true }
richmond-building-components = { workspace = true }
richmond-buildings = { workspace = true }
procedural-common = { workspace = true }

[lints]
workspace = true
