[package]
name = "maybraid-game-mode-training-ground"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[dependencies]
layer-stack = { workspace = true }
avian3d = { workspace = true }
bevy = { workspace = true }
building-components = { workspace = true }
building-physics = { workspace = true }
buildings = { workspace = true }
characters = { workspace = true }
character-items = { workspace = true }
chico = { workspace = true }
combat-hud = { workspace = true }
damage = { workspace = true }
durham = { workspace = true }
lod = { workspace = true }
mob-scenes = { workspace = true }
mob-characters = { workspace = true }
mob-intelligence = { workspace = true }
barking = { workspace = true }
mob-layer-model = { workspace = true }
player-camera = { workspace = true }
procedural-common = { workspace = true }
richmond = { workspace = true }
terrain-layer-model = { workspace = true }
urbanization-layer-model = { workspace = true }
vegetation-layer-model = { workspace = true }
world-player = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
character-persist = { workspace = true }
maybraid-game-mode-discover = { workspace = true }
threat-intelligence = { workspace = true }

[lints]
workspace = true
