[package]
name = "crozon-character-concepts-playground"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[dependencies]
bevy = { workspace = true }
bevy-character-ui-menu-renderer = { workspace = true }
camera-controls = { workspace = true }
character-ui-menu = { workspace = true }
clap = { workspace = true }
crozon-character-items = { workspace = true }
crozon-character-playground = { workspace = true }
crozon-character-ui-menus = { workspace = true }
crozon-characters = { workspace = true }
crozon-rigs = { workspace = true }
game-commands = { workspace = true }
lod = { workspace = true }
malo-animations = { workspace = true }
material-ref = { workspace = true }
scene-ref = { workspace = true }

[lints]
workspace = true
