//! Standard LOD generate / present / lazy-fulfill pipeline for terrain cells.

use std::collections::{HashMap, HashSet, VecDeque};
use std::marker::PhantomData;

use bevy::ecs::query::QueryFilter;
use bevy::ecs::system::SystemParam;
use bevy::math::bounding::{Aabb3d, IntersectsVolume};
use bevy::prelude::*;
use bevy::scene::prelude::{bsn, template_value, Scene};
use bevy::tasks::{AsyncComputeTaskPool, Task};
use durham_terrain::shaders::{DurhamTerrainShader, RefractionWater};
use futures::FutureExt;
use lod::gen::{
	GenerationScheme, Id, LodGeneratePlugin, LodGenerateQueue, LodGenerateRegionPlugin,
	LodGenerateSystems, LodScene, LodSceneCulls, LodSceneLevel, LodSceneStatus, OriginalId,
	RegionPresenter, SpatialIndex, StorageStatus, TrackedId, Version,
};
use lod::lod_ref::LodRef;
use lod::presentation::{
	LodPresentCullPlugin, LodPresentCullRegionPlugin, LodPresentPlugin, LodPresentQueue,
	LodPresentRegionPlugin, LodPresentSystems,
};
use lod::{
	cull_non_adjacent_bands, lod_host_scene_pending, LodChunkFulfillSystems, LodCullRegions,
	LodLazyPending, LodRefreshRegions, LodSceneRefreshRegionPlugin,
};
use lod_avian::AvianLodSceneRefreshPlugin;
use render_item::mesh::handle::Cached;

use crate::terrain::cell::{origin_cell_ids_for_layout, TerrainCellLayout, TerrainCellRing};
use crate::terrain::collider::{TerrainColliderHost, TerrainColliderMeshSource};
use crate::terrain::index::{AvianTerrainIndex, TerrainGenerationResult};
use crate::terrain::presentation::PresentedTerrainScene;
use crate::terrain::render::cascade_chunk_for_cell;
use crate::terrain::Terrain;
use crate::water::Water;

/// Cheap origin-cell descriptor generated by the standard LOD generation queue.
///
/// High level fulfillment emits a lazy terrain dispatch. The expensive semantic
/// terrain and mesh work happens after the LOD root exists, so
/// [`lod::LodLevelRootPending`] owns readiness and first-load lifetime.
#[derive(Component, Debug, Clone)]
pub struct TerrainLodCell {
	pub id: Id,
	pub cell: Aabb3d,
	pub stream_ring: Option<TerrainCellRing>,
}

impl TerrainLodCell {
	fn center(&self) -> Vec3 {
		(Vec3::from(self.cell.min) + Vec3::from(self.cell.max)) * 0.5
	}

	fn level_for(&self, viewer: &Transform) -> LodSceneLevel {
		self.stream_ring
			.map(|ring| ring.level_for(self.center(), viewer.translation))
			.unwrap_or(LodSceneLevel::High)
	}

	fn seeds_collision(&self) -> bool {
		self.stream_ring.is_none_or(|ring| ring.high_inner_radius <= 0.0)
	}
}

impl LodScene for TerrainLodCell {
	fn scene_lod_level(&self, lod_ref: &LodRef) -> LodSceneLevel {
		self.level_for(lod_ref.current_transform)
	}

	fn scene_lod_status(&self, lod_ref: &LodRef) -> LodSceneStatus {
		let previous = self.level_for(lod_ref.previous_transform);
		let current = self.level_for(lod_ref.current_transform);
		if previous == current {
			LodSceneStatus::Unchanged
		} else {
			LodSceneStatus::Changed(current)
		}
	}

	fn scene_lod_culls(&self, _lod_ref: &LodRef, current: LodSceneLevel) -> LodSceneCulls {
		cull_non_adjacent_bands(current)
	}

	fn scene_with_level(&self, _lod_ref: &LodRef, level: LodSceneLevel) -> impl Scene + 'static {
		if level != LodSceneLevel::High {
			return Box::new(()) as Box<dyn Scene>;
		}
		Box::new(bsn! {
			template_value(TerrainGenerationDispatch(self.id))
			TerrainGenerationLazy
			LodLazyPending
			Transform::default()
			Visibility::default()
		}) as Box<dyn Scene>
	}

	fn scene_bounds(&self) -> Aabb3d {
		let center = self.center();
		Aabb3d::from_min_max(Vec3::from(self.cell.min) - center, Vec3::from(self.cell.max) - center)
	}
}

#[derive(Clone)]
struct TerrainLodEntry {
	value: TerrainLodCell,
	bounds: Aabb3d,
	version: Version,
}

/// Spatial index of cheap terrain descriptors consumed by generic LOD plugins.
#[derive(Resource, Clone)]
pub struct TerrainLodIndex {
	layout: TerrainCellLayout,
	active_region: Option<Aabb3d>,
	next_version: u64,
	entries: HashMap<Id, TerrainLodEntry>,
}

impl Default for TerrainLodIndex {
	fn default() -> Self {
		Self {
			layout: TerrainCellLayout::default(),
			active_region: None,
			next_version: 0,
			entries: HashMap::new(),
		}
	}
}

impl TerrainLodIndex {
	fn next_version(&mut self) -> Version {
		self.next_version += 1;
		Version(self.next_version)
	}

	fn sync_layout(&mut self, layout: &TerrainCellLayout, active_region: Option<Aabb3d>) {
		if self.layout != *layout {
			self.layout = layout.clone();
			self.entries.clear();
		}
		self.active_region = active_region;
	}
}

impl SpatialIndex<TerrainLodCell> for TerrainLodIndex {
	fn tracked_ids_for(&self, region: Aabb3d) -> Vec<TrackedId> {
		self.entries
			.iter()
			.filter(|(_, entry)| region.intersects(&entry.bounds))
			.map(|(id, _)| TrackedId(*id))
			.collect()
	}

	fn storage_status(&self, id: Id) -> StorageStatus {
		if self.entries.contains_key(&id) {
			StorageStatus::TrackedWithin
		} else {
			StorageStatus::NotTracked
		}
	}

	fn get(&self, id: Id) -> Option<&TerrainLodCell> {
		self.entries.get(&id).map(|entry| &entry.value)
	}

	fn get_bounds(&self, id: Id) -> Option<Aabb3d> {
		self.entries.get(&id).map(|entry| entry.bounds)
	}

	fn version(&self, id: Id) -> Option<Version> {
		self.entries.get(&id).map(|entry| entry.version)
	}

	fn insert(&mut self, id: Id, value: TerrainLodCell, bounds: Aabb3d, _lod_ref: &LodRef) {
		let version = self.next_version();
		self.entries.insert(id, TerrainLodEntry { value, bounds, version });
	}
}

impl GenerationScheme<TerrainLodIndex> for TerrainLodCell {
	fn original_ids_for(index: &mut TerrainLodIndex, region: Aabb3d) -> Vec<OriginalId> {
		let coverage = index.active_region.unwrap_or(region);
		origin_cell_ids_for_layout(&index.layout, coverage)
			.into_iter()
			.filter(|OriginalId(id)| {
				id.origin_cell_bounds().is_some_and(|bounds| region.intersects(&bounds))
			})
			.collect()
	}

	fn build_with_id(
		index: &mut TerrainLodIndex,
		id: Id,
		_lod_ref: &LodRef,
	) -> Option<(Self, Aabb3d)> {
		let cell = id.origin_cell_bounds()?;
		let size = Vec3::from(cell.max - cell.min).x;
		let stream_ring = index.layout.stream_ring_for_cell_size(size);
		Some((Self { id, cell, stream_ring }, cell))
	}
}

#[derive(Debug, Clone, Copy, Component)]
struct TerrainGenerationDispatch(Id);

impl Default for TerrainGenerationDispatch {
	fn default() -> Self {
		Self(Id::Universal)
	}
}

#[derive(Debug, Clone, Copy, Component, Default)]
struct TerrainGenerationLazy;

#[derive(Debug, Clone, Copy, Component)]
struct TerrainMeshLazy;

#[derive(Debug, Clone, Copy, Component)]
struct WaterMeshLazy;

struct CompletedTerrainCell {
	id: Id,
	result: TerrainGenerationResult,
}

#[derive(Resource, Default)]
struct TerrainGenerationQueue {
	queued: VecDeque<(Entity, Id)>,
	queued_entities: HashSet<Entity>,
	in_flight: HashMap<Entity, Task<CompletedTerrainCell>>,
}

const TERRAIN_GENERATION_STARTS_PER_FRAME: usize = 2;
const TERRAIN_GENERATION_MAX_IN_FLIGHT: usize = 4;

#[derive(Debug, Clone, Copy)]
struct PresentedTerrainLod {
	version: Version,
	entity: Entity,
	hidden: bool,
}

#[derive(Resource, Default)]
struct TerrainLodPresenterState {
	presented: HashMap<Id, PresentedTerrainLod>,
}

/// Standard [`RegionPresenter`] that creates typed lazy terrain LOD hosts.
#[derive(SystemParam)]
pub struct TerrainLodPresenter<'w, 's> {
	commands: Commands<'w, 's>,
	state: ResMut<'w, TerrainLodPresenterState>,
	hosts: Query<'w, 's, (), With<TerrainLodCell>>,
}

impl RegionPresenter<TerrainLodCell, TerrainLodIndex> for TerrainLodPresenter<'_, '_> {
	fn presented_version(&self, id: Id) -> Option<Version> {
		self.state.presented.get(&id).map(|entry| entry.version)
	}

	fn handle(&mut self, id: Id, version: Version, value: &TerrainLodCell, lod_ref: &LodRef) {
		if let Some(previous) = self.state.presented.remove(&id) {
			self.commands.entity(previous.entity).despawn();
		}
		let transform = Transform::from_translation(value.center());
		let level = value.scene_lod_level(lod_ref);
		let entity = self
			.commands
			.spawn_scene((
				lod_host_scene_pending(level, value.scene_bounds()),
				bsn! {
					template_value(transform)
					Visibility::default()
				},
			))
			.insert((value.clone(), PresentedTerrainScene(id)))
			.id();
		if value.seeds_collision() {
			self.commands.entity(entity).insert(TerrainColliderHost);
		}
		self.state
			.presented
			.insert(id, PresentedTerrainLod { version, entity, hidden: false });
	}

	fn hide(&mut self, id: Id) {
		let Some(entry) = self.state.presented.get_mut(&id) else {
			return;
		};
		entry.hidden = true;
	}

	fn is_hidden(&self, id: Id) -> bool {
		self.state.presented.get(&id).is_some_and(|entry| entry.hidden)
	}

	fn presented_ids(&self) -> Vec<Id> {
		self.state.presented.keys().copied().collect()
	}

	fn remove_stale(&mut self, wanted: &HashSet<Id>) {
		let stale: Vec<_> = self
			.state
			.presented
			.iter()
			.filter(|(id, _)| !wanted.contains(id))
			.map(|(id, entry)| (*id, entry.entity))
			.collect();
		for (id, entity) in stale {
			self.commands.entity(entity).despawn();
			self.state.presented.remove(&id);
		}
	}

	fn needs_repair(&self, _region: Aabb3d, id: Id, _version: Version) -> bool {
		self.state
			.presented
			.get(&id)
			.is_none_or(|entry| entry.hidden || !self.hosts.contains(entry.entity))
	}
}

fn sync_terrain_lod_index<M: Send + Sync + 'static>(
	layout: Res<TerrainCellLayout>,
	keep: Res<lod::gen::LodGenerateKeepRegion<M>>,
	mut index: ResMut<TerrainLodIndex>,
	mut generate_queue: ResMut<LodGenerateQueue<TerrainLodCell>>,
	mut present_queue: ResMut<LodPresentQueue<TerrainLodCell>>,
) {
	let layout_changed = index.layout != *layout;
	index.sync_layout(&layout, keep.region);
	if layout_changed {
		generate_queue.clear();
		present_queue.clear();
	}
}

fn materialize_terrain_cell(
	commands: &mut Commands,
	entity: Entity,
	level_root: Entity,
	terrain: Terrain,
	water: Option<Water>,
) {
	let center = (Vec3::from(terrain.cell.min) + Vec3::from(terrain.cell.max)) * 0.5;
	let chunk = cascade_chunk_for_cell(terrain.cell, terrain.res_2);
	let transform = Transform::from_translation(chunk.origin - center);
	let builder = terrain.mesh_builder();
	let material = terrain.material.clone();
	let seeds_collision = terrain.stream_ring.is_none_or(|ring| ring.high_inner_radius <= 0.0);
	let mut target = commands.entity(entity);
	target
		.remove::<TerrainGenerationDispatch>()
		.remove::<TerrainGenerationLazy>()
		.insert((
			Name::new("Generated terrain mesh"),
			TerrainMeshLazy,
			transform,
			chunk,
			Cached::new(builder),
			MeshMaterial3d::<DurhamTerrainShader>(material),
		));
	if seeds_collision {
		target.insert(TerrainColliderMeshSource);
	}
	if let Some(water) = water {
		let chunk = cascade_chunk_for_cell(water.cell, water.res_2);
		commands.spawn((
			Name::new("Generated water mesh"),
			ChildOf(level_root),
			WaterMeshLazy,
			LodLazyPending,
			Transform::from_translation(chunk.origin - center),
			chunk,
			Cached::new(water.sdf),
			MeshMaterial3d::<RefractionWater>(water.material),
			Visibility::default(),
		));
	}
}

fn drive_terrain_generation(
	mut commands: Commands,
	mut queue: ResMut<TerrainGenerationQueue>,
	mut index: AvianTerrainIndex,
	added: Query<(Entity, &TerrainGenerationDispatch), Added<TerrainGenerationDispatch>>,
	parents: Query<&ChildOf>,
	live: Query<()>,
) {
	for (entity, dispatch) in &added {
		let level_root = parents.get(entity).map(ChildOf::parent).unwrap_or(entity);
		if let Some((terrain, water)) = index.generated_cell(dispatch.0) {
			materialize_terrain_cell(&mut commands, entity, level_root, terrain, water);
		} else if queue.queued_entities.insert(entity) {
			queue.queued.push_back((entity, dispatch.0));
		}
	}

	let completed: Vec<_> = queue
		.in_flight
		.iter_mut()
		.filter_map(|(entity, task)| (&mut *task).now_or_never().map(|result| (*entity, result)))
		.collect();
	for (entity, completed) in completed {
		queue.in_flight.remove(&entity);
		queue.queued_entities.remove(&entity);
		if !live.contains(entity) {
			continue;
		}
		index.apply_generation_batch(completed.result);
		if let Some((terrain, water)) = index.generated_cell(completed.id) {
			let level_root = parents.get(entity).map(ChildOf::parent).unwrap_or(entity);
			materialize_terrain_cell(&mut commands, entity, level_root, terrain, water);
		} else {
			commands
				.entity(entity)
				.remove::<TerrainGenerationDispatch>()
				.remove::<TerrainGenerationLazy>()
				.remove::<LodLazyPending>();
		}
	}

	let available = TERRAIN_GENERATION_MAX_IN_FLIGHT.saturating_sub(queue.in_flight.len());
	for _ in 0..available.min(TERRAIN_GENERATION_STARTS_PER_FRAME) {
		let Some((entity, id)) = queue.queued.pop_front() else {
			break;
		};
		if !live.contains(entity) {
			queue.queued_entities.remove(&entity);
			continue;
		}
		let input = index.generation_input();
		let task = AsyncComputeTaskPool::get().spawn(async move {
			CompletedTerrainCell { id, result: input.generate_ids(vec![id]) }
		});
		queue.in_flight.insert(entity, task);
	}
}

fn clear_generated_mesh_lazy(
	mut commands: Commands,
	pending: Query<(Entity, Has<TerrainMeshLazy>, Has<WaterMeshLazy>), With<LodLazyPending>>,
	children: Query<&Children>,
	meshes: Query<(), With<Mesh3d>>,
) {
	for (entity, terrain, water) in &pending {
		if !terrain && !water {
			continue;
		}
		let ready = children
			.get(entity)
			.is_ok_and(|children| children.iter().any(|child| meshes.contains(child)));
		if ready {
			let mut target = commands.entity(entity);
			target.remove::<LodLazyPending>();
			if terrain {
				target.remove::<TerrainMeshLazy>();
			}
			if water {
				target.remove::<WaterMeshLazy>();
			}
		}
	}
}

/// One standard LOD pipeline for terrain request generation, presentation,
/// lazy semantic generation, scene fulfillment, refresh, and culling.
pub struct TerrainLodPlugin<P, F, M>
where
	P: Resource + LodRefreshRegions + LodCullRegions + Default,
	F: QueryFilter + 'static,
	M: Send + Sync + 'static,
{
	_marker: PhantomData<fn() -> (P, F, M)>,
}

impl<P, F, M> Default for TerrainLodPlugin<P, F, M>
where
	P: Resource + LodRefreshRegions + LodCullRegions + Default,
	F: QueryFilter + 'static,
	M: Send + Sync + 'static,
{
	fn default() -> Self {
		Self { _marker: PhantomData }
	}
}

impl<P, F, M> Plugin for TerrainLodPlugin<P, F, M>
where
	P: Resource + LodRefreshRegions + LodCullRegions + Default,
	F: QueryFilter + 'static,
	M: Send + Sync + 'static,
{
	fn build(&self, app: &mut App) {
		app.init_resource::<TerrainLodIndex>()
			.init_resource::<TerrainLodPresenterState>()
			.init_resource::<TerrainGenerationQueue>()
			.add_plugins(LodGenerateRegionPlugin::<P, F, M>::default())
			.add_plugins(LodGeneratePlugin::<TerrainLodCell, TerrainLodIndex, M, F>::default())
			.add_plugins(LodPresentRegionPlugin::<P, F, M>::default())
			.add_plugins(LodPresentPlugin::<
				TerrainLodCell,
				TerrainLodIndex,
				TerrainLodPresenter,
				M,
				F,
			>::default())
			.add_plugins(LodPresentCullRegionPlugin::<P, F, M>::default())
			.add_plugins(LodPresentCullPlugin::<
				TerrainLodCell,
				TerrainLodIndex,
				TerrainLodPresenter,
				M,
			>::default())
			.add_plugins(LodSceneRefreshRegionPlugin::<P, F, M>::default())
			.add_plugins(AvianLodSceneRefreshPlugin::<TerrainLodCell, M, F>::default())
			.add_systems(Update, sync_terrain_lod_index::<M>.before(LodGenerateSystems::Drain))
			.add_systems(
				Update,
				(drive_terrain_generation, clear_generated_mesh_lazy)
					.chain()
					.after(LodChunkFulfillSystems::Drain)
					.before(LodChunkFulfillSystems::Complete),
			)
			.configure_sets(Update, LodPresentSystems::Produce.after(LodGenerateSystems::Drain));
	}
}
