[package]
name = "bevy-character-ui-menu-renderer"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[dependencies]
bevy = { workspace = true }
character-ui-menu = { workspace = true }
crozon-character-ui-menus = { workspace = true }

[lints]
workspace = true
