[package]
name = "geneva"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[dependencies]
bevy = { workspace = true }
building-components = { workspace = true }
chico = { workspace = true }
comproc = { workspace = true }
durham = { workspace = true }
procedural-common = { workspace = true }
lod = { workspace = true }
maybraid-language-core = { workspace = true }
maybraid-language-grammars = { workspace = true }
noise = { workspace = true }
richmond = { workspace = true }
urbanization-cells = { workspace = true }
urbanization-layer-model = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
terrain-layer-model = { workspace = true }
terrain-stamps = { workspace = true }
terrain-watersheds = { workspace = true }

[lints]
workspace = true
