[package]
name = "chico-bumpout-playground"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[[bin]]
name = "chico-bumpout-playground"
path = "src/main.rs"

[dependencies]
bevy = { workspace = true }
chico-bumpout = { workspace = true }
clap = { workspace = true }
game-commands = { workspace = true }
lod-cascade = { workspace = true }
material-ref = { workspace = true }
procedural-common = { workspace = true }
render-item = { workspace = true }
sdf = { workspace = true }
terrain-chunk-ref = { workspace = true }

[lints]
workspace = true
