//! Shared humanoid asset catalog used by multiple species.

pub mod assets;
pub mod bsn;

pub use assets::{
	BodyMesh, EarMesh, EyeMesh, HairMesh, HeadMesh, MouthMesh, NoseMesh, BODY_DRAGLOON, BODY_FULL,
	BODY_GUMBUS, BODY_RIG, BODY_STANDARD, EAR_FLANK, EAR_ROUND, EAR_STANDARD, EYE_FALCON,
	EYE_STANDARD, HEAD_CANINE, HEAD_FULL, HEAD_GAUNT, HEAD_ORTHO_BEAR, HEAD_RIG, HEAD_STANDARD,
	HORNS_HARROWED_CROWN, HORNS_LORKEN_CROWN, MOUTH_CANINE_SNOUT, MOUTH_LERODON_SNOUT,
	MOUTH_STANDARD, NOSE_BALLOON, NOSE_BROAD, NOSE_LOAF, NOSE_STANDARD, PRONOGRADE_HEAD_RIG,
	QUADRUPED_RIG, TAIL_CAT, TAIL_LERODON,
};
