[package]
name = "firing-range-playground"
version = { workspace = true }
edition = { workspace = true }
license  = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[[bin]]
name = "firing-range"
path = "src/main.rs"

[dependencies]
avian3d = { workspace = true }
bevy = { workspace = true }
clap = { workspace = true }
crozon-character-items = { workspace = true }
crozon-character-ragdoll = { workspace = true }
crozon-characters = { workspace = true }
firearm-intelligence = { workspace = true }
firearm-user = { workspace = true }
firearms = { workspace = true }
damage = { workspace = true }
game-commands = { workspace = true }
lod = { workspace = true }
lod-avian = { workspace = true }
material-ref = { workspace = true }
maybraid-character-controller = { workspace = true }
maybraid-input = { workspace = true }
movement-intelligence = { workspace = true }
movement-intelligence-avian = { workspace = true }
movement-intelligence-richmond = { workspace = true }
movement-realization = { workspace = true }
player = { workspace = true }
player-camera = { workspace = true }
procedural-common = { workspace = true }
richmond-building-components = { workspace = true }
richmond-building-physics = { workspace = true }
richmond-buildings = { workspace = true }
richmond-developments = { workspace = true }

[lints]
workspace = true
