[package]
name = "chico-vegetation-on-terrain-playground"
version = { workspace = true }
edition  = { workspace = true }
license  = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[[bin]]
name = "chico-vegetation-on-terrain"
path = "src/main.rs"

[dependencies]
bevy = { workspace = true }
durham-terrain = { workspace = true }
durham-terrain-models = { workspace = true }
chico-groves = { workspace = true, features = ["render"] }
chico-forests = { workspace = true }
chico-vegetation-components = { workspace = true }
chico-bumpout = { workspace = true }
chico-sbs-trees-playground = { path = "../sbs-trees-playground" }
lod = { workspace = true }
lod-avian = { workspace = true }
lod-cascade = { workspace = true }
avian3d = { workspace = true }
crozon-characters = { workspace = true }
ground-avian = { workspace = true }
render-item = { workspace = true }
terrain-chunk-ref = { workspace = true }
clap = { workspace = true }
game-commands = { workspace = true }
log = { workspace = true }
procedural-common = { workspace = true, features = ["clap"] }

[lints]
workspace = true
