[package]
name = "mob-layer-presentation"
version = { workspace = true }
edition  = { workspace = true }
license  = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[dependencies]
layer-stack = { workspace = true }
bevy = { workspace = true }
lod = { workspace = true }
lod-gimme = { workspace = true }
mob-scenes = { workspace = true }
mob-intelligence = { workspace = true }
barking = { workspace = true }
mob-layer-model = { workspace = true }
terrain-layer-model = { workspace = true }
urbanization-layer-model = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
durham = { workspace = true }
richmond = { workspace = true }
urbanization-cells = { workspace = true }

[lints]
workspace = true
