[package]
name = "lod-visual-pbr"
version = { workspace = true }
edition  = { workspace = true }
license  = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[dependencies]
bevy = { workspace = true }
bytemuck = { version = "1", features = ["derive"] }
chico-vegetation-components = { workspace = true }
lod = { workspace = true }
material-ref = { workspace = true }
scene-ref = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }

[lints]
workspace = true
