[package]
name = "maybraid-mobs"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[dependencies]
bevy = { workspace = true }
damage = { workspace = true }
journeying-intelligence = { workspace = true }
lod = { workspace = true }
mob-characters = { workspace = true }
mob-intelligence = { workspace = true }
poi-intelligence = { workspace = true }
tether-intelligence = { workspace = true }
threat-intelligence = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }

[lints]
workspace = true
