[package]
name = "vegetation-layer-presentation"
version = { workspace = true }
edition  = { workspace = true }
license  = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[dependencies]
bevy = { workspace = true }
chico-bumpout = { workspace = true }
chico-forests = { workspace = true }
chico-groves = { workspace = true }
chico-vegetation-shaders = { workspace = true }
durham-terrain-models = { workspace = true }
lod = { workspace = true }
lod-cascade = { workspace = true }
material-ref = { workspace = true }
procedural-common = { workspace = true }
render-item = { workspace = true }
terrain-chunk-ref = { workspace = true }
terrain-layer-model = { workspace = true }
vegetation-layer-model = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
richmond-development-models = { workspace = true }
richmond-urbanization = { workspace = true }
urbanization-layer-model = { workspace = true }

[lints]
workspace = true
