[package]
name = "terrain-chunk-ref"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[dependencies]
bevy = { workspace = true }
chunk = { workspace = true }
lod-cascade = { workspace = true }
render-item = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }

[lints]
workspace = true
