[package]
name = "richmond-developments-on-terrain-playground"
version = { workspace = true }
edition  = { workspace = true }
license  = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[[bin]]
name = "richmond-developments-on-terrain"
path = "src/main.rs"

[dependencies]
bevy = { workspace = true }
clap = { workspace = true }
durham-terrain = { workspace = true }
durham-terrain-models = { workspace = true }
game-commands = { workspace = true }
log = { workspace = true }
lod = { workspace = true }
render-item = { workspace = true }
richmond-building-components = { workspace = true }
richmond-buildings = { workspace = true }
richmond-development-models = { workspace = true }
richmond-developments = { workspace = true }

[lints]
workspace = true
