[package]
name = "chico-tree-components"
version = { workspace = true }
edition  = { workspace = true }
license  = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[dependencies]
bevy = { workspace = true }
chico-ball-components = { workspace = true }
chico-stick-components = { workspace = true }
chico-sbs-geometry = { workspace = true, features = ["render"] }
procedural-common = { workspace = true }
render-item = { workspace = true }
clap = { workspace = true, optional = true }

[dev-dependencies]
anyhow = { workspace = true }

[features]
default = []
clap = ["dep:clap", "chico-ball-components/clap", "procedural-common/clap"]

[lints]
workspace = true
