[package]
name = "renderit"
version = { workspace = true }
edition  = { workspace = true }
license  = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
log = { workspace = true }
rayon = { workspace = true }
lz4_flex = { workspace = true }
bincode = { workspace = true }

bevy = { workspace = true, features = ["serialize"] }
sdf = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }

[lints]
workspace = true
