[package]
name = "maybraid"
version = { workspace = true }
edition  = { workspace = true }
license  = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[[bin]]
name = "maybraid"
path = "src/main.rs"

[dependencies]
layer-stack = { workspace = true }
bevy = { workspace = true }
clap = { workspace = true }
character-model-user = { workspace = true }
characters-playground = { workspace = true }
character-inventory-user = { workspace = true }
maybraid-character-controller = { workspace = true }
maybraid-game-mode-discover = { workspace = true }
maybraid-game-mode-reliquary = { workspace = true }
maybraid-input = { workspace = true }
maybraid-menu-controller = { workspace = true }
maybraid-world = { workspace = true }
menu-components = { workspace = true }
menu-playground = { workspace = true }
menu-screens = { workspace = true }
character-persist = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
character-items = { workspace = true }
characters = { workspace = true }
lod = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
