[package]
name = "maybraid"
version = { workspace = true }
edition  = { workspace = true }
license  = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[[bin]]
name = "maybraid"
path = "src/main.rs"

[dependencies]
bevy = { workspace = true }
crozon-character-playground = { workspace = true }
maybraid-character-controller = { workspace = true }
maybraid-input = { workspace = true }
maybraid-menu-controller = { workspace = true }
maybraid-world = { workspace = true }
menu-components = { workspace = true }
menu-playground = { workspace = true }
menu-screens = { workspace = true }

[lints]
workspace = true
