[package]
name = "maybraid-world-playground"
version = { workspace = true }
edition  = { workspace = true }
license  = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[[bin]]
name = "maybraid-world"
path = "src/main.rs"

[dependencies]
bevy = { workspace = true }
maybraid-input = { workspace = true }
maybraid-world = { workspace = true }

[lints]
workspace = true
