[package]
name = "crozon-character-playground"
version = { workspace = true }
edition  = { workspace = true }
license  = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[dependencies]
bevy = { workspace = true }
camera-controls = { workspace = true }
clap = { workspace = true }
crozon-rigs = { workspace = true }
game-commands = { workspace = true }
log = { workspace = true }
malo-animations = { workspace = true }

[lints]
workspace = true
